// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/common/constants': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/constants').default>>>>
    }
    '/api/common/methods': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/methods').default>>>>
    }
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/profile': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile').default>>>>
    }
    '/api/submission-created': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/submission-created').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}