[build]
  publish = "dist"
  command = "pnpm run build"
  functions = "functions/"

[dev]
  targetPort = 8080
  autoLaunch = false
  command = "quasar dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "*"