import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.0.11',
  date: '2023-01-09T13:15:42.423Z',
};
export default meta;
