import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.0.11',
  date: '2023-03-08T18:36:35.132Z',
};
export default meta;
